---
apiVersion: apps/v1
kind: Deployment
metadata: 
 name: foo
spec:
 replicas: 3
 strategy:
  type: RollingUpdate
  rollingUpdate:
   maxUnavailable: 1
   maxSurge: 1
 selector:
  matchLabels:
   app: foo
 template:
  metadata:
   labels: 
    app: foo
  spec:
   containers:
    - name: app
      image: dgkanatsios/simpleapp
      resources:
            limits:
              cpu: 10m
      ports:
       - containerPort: 8080
